### ISSUE TITLE
Document how to to multiple sites in 1 index

### ISSUE THREAD

**Issue by riasvdv** [riasvdv/craft-scout#97]
- Use `->site('*')` in criteria
- Make sure to return unique `objectID` from transformer
- Add an example

**Comment by mustasj** [comment]
I just started making indices for this!
Can i do this now or dot you have to do some code changes?

**Comment by riasvdv** [comment]
Should all be possible, just not documented everything yet!

**Comment by mustasj** [comment]
Doesn't seem to work. if i use `->site('*')` it still only indexes the default site.
But saw a new issue came in now: #98

**Comment by riasvdv** [comment]
Yeah, it will be fixed when #99 is merged, a little oversight I had when rewriting

**Comment by davist11** [comment]
How would this work? If I have an entry that is enabled for two sites, it only pushes one record to Algolia. I even tried passing in a unique `objectID`

```php
$indices[] = ScoutIndex::create(CRAFT_ENVIRONMENT . '_Search')
    ->elementType(Entry::class)
    ->criteria(function (EntryQuery $query) {
        return $query->section([
            'news',
            'pressReleases',
            'pages',
            'resources',
            'events',
        ])
        ->siteId([
            Craft::$app->sites->getSiteByHandle('en')->id,
            Craft::$app->sites->getSiteByHandle('es')->id,
        ]);
    })
    ->transformer(function (Entry $entry) {
        return [
            'objectID' => implode('_', [
                $entry->id,
                $entry->site->handle,
            ]),
            'title' => $entry->title,
            'url' => $entry->url,
        ];
    });
```

**Comment by timkelty** [comment]
@davist11 can you test with this branch? Should be fixed.

```
"rias/craft-scout": "97-multisite-single-index as 2.3.2",
```

You've got the right idea with including your site in you objectID.
The issue stems from when before Craft allowed for querying multiple sites in a single query.

Unrelated: you could just pass `site(['en', 'es'])` in yoru query, instead of getting the ids yourself.

**Comment by davist11** [comment]
Hmm, is that branch name correct?

```
  [UnexpectedValueException]                                                                                           
  Could not parse version constraint 97-multisite-single-index as 2.3.2: Invalid version string "97-multisite-single-  
  index" in "97-multisite-single-index as 2.3.2", the alias source must be an exact version, if it is a branch name y  
  ou should prefix it with dev-     
```

> Unrelated: you could just pass site(['en', 'es']) in yoru query, instead of getting the ids yourself.

Niiiice thanks

**Comment by timkelty** [comment]
whoops - use `dev-97-multisite-single-index`

**Comment by davist11** [comment]
Hmm, I'm still not seeing the spanish version getting created in Algolia. Dunno if the new distinct stuff I've added would have impacted that at all. Here's my index

```php
$indices[] = ScoutIndex::create(CRAFT_ENVIRONMENT . '_Search')
    ->elementType(Entry::class)
    ->criteria(function (EntryQuery $query) {
        return $query->section([
            'news',
            'pressReleases',
            'pages',
            'resources',
            'events',
        ])
        ->site([
            'en',
            'es'
        ]);
    })
    ->transformer(function (Entry $entry) {
        return [
            'objectID' => implode('_', [
                $entry->id,
                $entry->site->handle,
            ]),
            'title' => $entry->title,
            'url' => $entry->url,
            'summary' => self::_formatSummary($entry),
            'postDate' => self::_formatDate($entry->postDate),
            'expirationDate' => self::_formatDate($entry->expiryDate),
            'dateUpdated' => self::_formatDate($entry->dateUpdated),
            'type' => self::_formatType($entry),
            'eyebrow' => self::_formatEyebrow($entry->section->name),
            'content' => self::_formatPageBlocks($entry->pageBlocks),
        ];
    })
    ->splitElementsOn([
        'content',
    ])
    ->indexSettings(IndexSettings::create()
        ->hitsPerPage(10)
        ->attributeForDistinct('distinctID')
        ->distinct(true)
        ->attributesForFaceting([
            'type',
            'distinctID',
        ])
        ->replicas([
            CRAFT_ENVIRONMENT . '_Search_dateAsc',
            CRAFT_ENVIRONMENT . '_Search_dateDesc',
        ])
    );
```

**Comment by timkelty** [comment]
@davist11 weird…I'm using your $indices and it's working for me…

As a sanity check, can you go to your plugins page and make sure it looks like:
![Screen Shot 2020-07-09 at 11 44 35 AM](https://user-images.githubusercontent.com/18329/87061333-9def6f80-c1d9-11ea-8b97-04f81acbf2fa.png)

> Dunno if the new distinct stuff I've added would have impacted that at all

Hmm could be…what are you trying to do there? As it is, your transformer doesn't define a `distinctID`, so references to it aren't going to work. In fact they're probably just seeing it always as `null` and not indexing.  Since all elements will have unique objectIDs, you shouldn't need any of the distinct stuff, if you're just want a 1-1 match of entry to algolia object.

**Comment by davist11** [comment]
> As a sanity check, can you go to your plugins page and make sure it looks like

Confirmed

> As it is, your transformer doesn't define a distinctID

That value automatically gets added (per the Scout documentation and what I'm seeing in Algolia records). I tried removing the distinct stuff and still not seeing the spanish version.

**Comment by davist11** [comment]
Is every entry (from each site) being passed separately to the transformer?

**Comment by timkelty** [comment]
> Is every entry (from each site) being passed separately to the transformer?

Yes - everything from the criteria gets passed to the transformer, so unless you have a [unique](https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#parameters) parm on your criteria, you'll get back the elements from each site.

**Comment by timkelty** [comment]
> That value automatically gets added (per the Scout documentation and what I'm seeing in Algolia records).

derp – right you are.

If its possible to share your composer files and db, that'd be helpful. Or even sync to a project.yaml file…

**Comment by davist11** [comment]
Sent, thanks!

**Comment by jornwildenbeest** [comment]
What is the status for this issue?

Is this available in the main branch?
